apiVersion: v1
kind: Service
metadata:
  name: sriov-network-metrics-exporter-service
  namespace: {{.Namespace}}
  annotations:
    prometheus.io/target: "true"
spec:
  selector:
    app.kubernetes.io/name: sriov-metrics-exporter
  ports:
    - protocol: TCP
      port: 9808
      targetPort: 9808
