apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/name: sriov-network-metrics-exporter
  name: sriov-network-metrics-exporter
  namespace: {{.Namespace}}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: sriov-network-metrics-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sriov-network-metrics-exporter
    spec:
      hostNetwork: true
      {{- if .ImagePullSecrets }}
      imagePullSecrets:
      {{- range .ImagePullSecrets }}
      - name: {{ . }}
      {{- end }}
      {{- end }}
      containers:
      - args:
        - --path.kubecgroup=/host/kubecgroup
        - --path.sysbuspci=/host/sys/bus/pci/devices/
        - --path.sysclassnet=/host/sys/class/net/
        - --path.cpucheckpoint=/host/cpu_manager_state
        - --path.kubeletsocket=/host/kubelet.sock
        - --collector.kubepoddevice=true
        - --collector.vfstatspriority=sysfs,netlink
        image: {{.Image}}
        name: metrics-exporter
        resources:
          requests:
            memory: 100Mi
            cpu: 100m
        securityContext:
          capabilities:
            drop:
              - ALL      
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
        volumeMounts:
        - mountPath: /host/kubelet.sock
          name: kubeletsocket
        - mountPath: /host/sys/bus/pci/devices
          name: sysbuspcidevices
          readOnly: true
        - mountPath: /host/sys/devices
          name: sysdevices
          readOnly: true
        - mountPath: /host/sys/class/net
          name: sysclassnet
          readOnly: true
        - mountPath: /host/kubecgroup
          name: kubecgroup
          readOnly: true
        - mountPath: /host/cpu_manager_state
          name: cpucheckpoint
          readOnly: true
        - name: sriov-network-metrics-exporter-config
          mountPath: /etc/sriov-network-metrics-exporter
      nodeSelector:
        kubernetes.io/os: linux
        node-role.kubernetes.io/worker: ""
      restartPolicy: Always
      volumes:
      - hostPath:
          path: /var/lib/kubelet/pod-resources/kubelet.sock
          type: "Socket"
        name: kubeletsocket
      - hostPath:
          path: /sys/fs/cgroup/cpuset/kubepods.slice/
          type: "Directory"
        name: kubecgroup
      - hostPath:
          path: /var/lib/kubelet/cpu_manager_state
          type: "File"
        name: cpucheckpoint
      - hostPath:
          path: /sys/class/net
          type: "Directory"
        name: sysclassnet
      - hostPath:
          path: /sys/bus/pci/devices
          type: "Directory"
        name: sysbuspcidevices
      - hostPath:
          path: /sys/devices
          type: "Directory"
        name: sysdevices
      - name: sriov-network-metrics-exporter-config
        configMap:
          name: sriov-network-metrics-exporter-config
