
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - sriovnetwork.k8s.cni.cncf.io
  resources:
  - sriovibnetworks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sriovnetwork.k8s.cni.cncf.io
  resources:
  - sriovibnetworks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - sriovnetwork.k8s.cni.cncf.io
  resources:
  - sriovnetworknodepolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sriovnetwork.k8s.cni.cncf.io
  resources:
  - sriovnetworknodepolicies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - sriovnetwork.k8s.cni.cncf.io
  resources:
  - sriovnetworknodepolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sriovnetwork.k8s.cni.cncf.io
  resources:
  - sriovnetworknodepolicies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - sriovnetwork.k8s.cni.cncf.io
  resources:
  - sriovnetworks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sriovnetwork.k8s.cni.cncf.io
  resources:
  - sriovnetworks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - sriovnetwork.k8s.cni.cncf.io
  resources:
  - sriovoperatorconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sriovnetwork.k8s.cni.cncf.io
  resources:
  - sriovoperatorconfigs/status
  verbs:
  - get
  - patch
  - update
