# permissions for end users to edit sriovnetworknodepolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sriovnetworknodepolicy-editor-role
rules:
- apiGroups:
  - sriovnetwork.k8s.cni.cncf.io
  resources:
  - sriovnetworknodepolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sriovnetwork.k8s.cni.cncf.io
  resources:
  - sriovnetworknodepolicies/status
  verbs:
  - get
