# permissions for end users to view sriovnetworknodestates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sriovnetworknodestate-viewer-role
rules:
- apiGroups:
  - sriovnetwork.k8s.cni.cncf.io
  resources:
  - sriovnetworknodestates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sriovnetwork.k8s.cni.cncf.io
  resources:
  - sriovnetworknodestates/status
  verbs:
  - get
