// Code generated by MockGen. DO NOT EDIT.
// Source: patcher.go
//
// Generated by this command:
//
//	mockgen -destination mock/mock_patcher.go -source patcher.go
//

// Package mock_status is a generated GoMock package.
package mock_status

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// MockInterface is a mock of Interface interface.
type MockInterface struct {
	ctrl     *gomock.Controller
	recorder *MockInterfaceMockRecorder
	isgomock struct{}
}

// MockInterfaceMockRecorder is the mock recorder for MockInterface.
type MockInterfaceMockRecorder struct {
	mock *MockInterface
}

// NewMockInterface creates a new mock instance.
func NewMockInterface(ctrl *gomock.Controller) *MockInterface {
	mock := &MockInterface{ctrl: ctrl}
	mock.recorder = &MockInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInterface) EXPECT() *MockInterfaceMockRecorder {
	return m.recorder
}

// PatchStatus mocks base method.
func (m *MockInterface) PatchStatus(ctx context.Context, obj client.Object, patch client.Patch) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PatchStatus", ctx, obj, patch)
	ret0, _ := ret[0].(error)
	return ret0
}

// PatchStatus indicates an expected call of PatchStatus.
func (mr *MockInterfaceMockRecorder) PatchStatus(ctx, obj, patch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PatchStatus", reflect.TypeOf((*MockInterface)(nil).PatchStatus), ctx, obj, patch)
}

// UpdateStatus mocks base method.
func (m *MockInterface) UpdateStatus(ctx context.Context, obj client.Object, updateFunc func() error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, obj, updateFunc)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockInterfaceMockRecorder) UpdateStatus(ctx, obj, updateFunc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockInterface)(nil).UpdateStatus), ctx, obj, updateFunc)
}

// UpdateStatusWithEvents mocks base method.
func (m *MockInterface) UpdateStatusWithEvents(ctx context.Context, obj client.Object, oldConditions, newConditions []v1.Condition, updateFunc func() error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatusWithEvents", ctx, obj, oldConditions, newConditions, updateFunc)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatusWithEvents indicates an expected call of UpdateStatusWithEvents.
func (mr *MockInterfaceMockRecorder) UpdateStatusWithEvents(ctx, obj, oldConditions, newConditions, updateFunc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatusWithEvents", reflect.TypeOf((*MockInterface)(nil).UpdateStatusWithEvents), ctx, obj, oldConditions, newConditions, updateFunc)
}
