name: "Merge on lgtm label"
on:
  workflow_run:
    workflows: ["Go", "Pull Request Labeler"]
    types:
      - completed
      - requested

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: zwaldowski/match-label-action@v1
        with:
          allowed: >
            lgtm
  mergepal-merge: # run merge pal in the end
    runs-on: ubuntu-latest
    needs:
      # make sure all required jobs are listed here
      - label
    steps:
      - uses: actions/checkout@v1
      - uses: maxkomarychev/merge-pal-action@vX.Y.Z
        with:
          token: ${{ secrets.GITHUB_TOKEN }}