name: "Merge on lgtm label"
on:
  workflow_run:
    workflows: ["Go", "Pull Request Labeler"]
    types:
      - completed
      - requested

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: mheap/github-action-required-labels@v1.1.2
        with:
          mode: exactly
          count: 1
          labels: "lgtm"
